# Generated by Django 6.0 on 2026-03-19 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0017_alter_competitionnotice_series_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueticket',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], db_index=True, default='public', max_length=20),
        ),
        migrations.CreateModel(
            name='CompetitionPracticeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('series', models.CharField(choices=[('icpc', 'ICPC'), ('ccpc', 'CCPC')], db_index=True, max_length=20)),
                ('stage', models.CharField(choices=[('network', 'Network'), ('regional', 'Regional'), ('invitational', 'Invitational'), ('provincial', 'Provincial')], db_index=True, max_length=20)),
                ('short_name', models.CharField(max_length=120)),
                ('official_name', models.CharField(max_length=500)),
                ('official_url', models.URLField(blank=True, max_length=500)),
                ('event_date', models.DateField(blank=True, db_index=True, null=True)),
                ('event_date_text', models.CharField(blank=True, max_length=80)),
                ('organizer', models.CharField(blank=True, max_length=255)),
                ('practice_links', models.JSONField(blank=True, default=list)),
                ('practice_links_note', models.CharField(blank=True, max_length=255)),
                ('source_file', models.CharField(blank=True, max_length=120)),
                ('source_section', models.CharField(blank=True, max_length=180)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_competition_practice_links', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_competition_practice_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionPracticeLinkProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_year', models.PositiveIntegerField(db_index=True)),
                ('proposed_series', models.CharField(choices=[('icpc', 'ICPC'), ('ccpc', 'CCPC')], db_index=True, max_length=20)),
                ('proposed_stage', models.CharField(choices=[('network', 'Network'), ('regional', 'Regional'), ('invitational', 'Invitational'), ('provincial', 'Provincial')], db_index=True, max_length=20)),
                ('proposed_short_name', models.CharField(max_length=120)),
                ('proposed_official_name', models.CharField(max_length=500)),
                ('proposed_official_url', models.URLField(blank=True, max_length=500)),
                ('proposed_event_date', models.DateField(blank=True, db_index=True, null=True)),
                ('proposed_event_date_text', models.CharField(blank=True, max_length=80)),
                ('proposed_organizer', models.CharField(blank=True, max_length=255)),
                ('proposed_practice_links', models.JSONField(blank=True, default=list)),
                ('proposed_practice_links_note', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_practice_link_proposals', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_competition_practice_link_proposals', to=settings.AUTH_USER_MODEL)),
                ('target_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='wiki.competitionpracticelink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
