# Generated by Django 6.0 on 2026-03-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0018_issueticket_visibility_competitionpracticelink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('visible', 'Visible'), ('hidden', 'Hidden')], default='visible', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('closed', 'Closed'), ('hidden', 'Hidden')], default='open', max_length=20),
        ),
    ]
