# Generated by Django 6.0 on 2026-04-09 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0026_merge_0024_headernavigationitem_0025_question_auto_close_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=80)),
                ('assistant_name', models.CharField(default='AlgoWiki 助手', max_length=80)),
                ('provider', models.CharField(choices=[('deepseek', 'DeepSeek')], db_index=True, default='deepseek', max_length=20)),
                ('base_url', models.URLField(default='https://api.deepseek.com', max_length=500)),
                ('model_name', models.CharField(default='deepseek-chat', max_length=120)),
                ('api_key_encrypted', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('show_launcher', models.BooleanField(default=True)),
                ('temperature', models.FloatField(default=0.3)),
                ('max_output_tokens', models.PositiveIntegerField(default=1024)),
                ('request_timeout_seconds', models.PositiveSmallIntegerField(default=30)),
                ('welcome_message', models.TextField(blank=True)),
                ('suggested_questions', models.JSONField(blank=True, default=list)),
                ('system_prompt', models.TextField(blank=True)),
                ('daily_request_limit', models.PositiveIntegerField(default=0)),
                ('daily_token_limit', models.PositiveIntegerField(default=0)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_success', models.BooleanField(blank=True, null=True)),
                ('last_test_message', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assistant_provider_configs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_assistant_provider_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssistantInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('provider', models.CharField(blank=True, db_index=True, max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('prompt_chars', models.PositiveIntegerField(default=0)),
                ('response_chars', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('response_ms', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_interaction_logs', to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_logs', to='wiki.assistantproviderconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
