# Generated by Django 6.0 on 2026-04-10 00:00

from django.db import migrations, models


def seed_questions_header_nav(apps, schema_editor):
    HeaderNavigationItem = apps.get_model("wiki", "HeaderNavigationItem")
    HeaderNavigationItem.objects.update_or_create(
        key="questions",
        defaults={
            "title": "问答",
            "display_order": 35,
            "is_visible": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0027_assistantproviderconfig_assistantinteractionlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="headernavigationitem",
            name="key",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("competition-wiki", "Competition Wiki"),
                    ("competitions", "Competition Zone"),
                    ("questions", "Q&A"),
                    ("about", "About AlgoWiki"),
                    ("friendly-links", "Friendly Links"),
                ],
                db_index=True,
                max_length=40,
                unique=True,
            ),
        ),
        migrations.RunPython(seed_questions_header_nav, migrations.RunPython.noop),
    ]
