# Generated by Django 6.0 on 2026-04-14 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0031_revisionproposal_base_content_md_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionnotice',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='competitionnotice',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitionnotice',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_competition_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competitionnotice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='competitionscheduleentry',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='competitionscheduleentry',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitionscheduleentry',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_competition_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competitionscheduleentry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=20),
        ),
    ]
